version: '3.8'

networks:
  shortener_network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - shortener_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shortener_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shortener_network

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5086:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - shortener_network
    depends_on:
      - shortenerservice

  shortenerservice:
    build:
      context: ./ShortenerService
      dockerfile: Dockerfile
    container_name: shortenerservice
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqlserver,1433;Database=ShortUrlDB;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
      - ConnectionStrings:RedisConnection=redis:6379
      - ConnectionStrings:RabbitMQConnection=amqp://guest:guest@rabbitmq:5672/
      - JwtSettings:Secret=THIS_IS_A_VERY_LONG_AND_STRONG_SECRET_KEY_FOR_JWT_AUTHENTICATION_AND_MUST_BE_KEPT_CONFIDENTIAL
      - JwtSettings:Issuer=ShortenerApp
      - JwtSettings:Audience=ShortenerApp.Client
    networks:
      - shortener_network
    depends_on:
      - sqlserver
      - redis
      - rabbitmq

  webapp:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8080:80"
    networks:
      - shortener_network
    depends_on:
      - api-gateway

volumes:
  sqlserver_data:
  redis_data:
  rabbitmq_data: